### ISSUE TITLE
Line break in replace

### ISSUE THREAD

**Issue by rlacerda83** [JoshData/pdf-redactor#12]
Hello!

I'm having trouble with the line break.

If you replace a small string with a long string, some of the content is not visible in the PDF, because there is no line break.

Do you have any suggestions to adjust this?

**Comment by JoshData** [comment]
I don't, unfortunately. `pdfrw` doesn't provide a mechanism to know the geometry of the text being replaced, so there's probably no reasonable way to address that problem.

**Comment by rlacerda83** [comment]
OK! Thank you!
